name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and release binaries
    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ github.ref_name }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
            archive_ext: zip
          - os: windows-latest
            goos: windows
            goarch: amd64
            ext: .exe
            archive_ext: zip
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
            archive_ext: tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-X main.version=${{ env.VERSION }}" -o dist/f1viewer${{ matrix.ext }}

      - name: Archive release
        run: |
          cd dist
          if [ "${{ matrix.archive_ext }}" = "zip" ]; then
            zip f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }} f1viewer${{ matrix.ext }}
          else
            tar -czf f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }} f1viewer
          fi

      - name: Generate checksums
        run: |
          cd dist
          shasum -a 256 f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }} > f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }}.sha256

      - name: Install FPM (for .deb and .rpm)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential rpm
          sudo gem install --no-document fpm

      - name: Build .deb and .rpm packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p pkg/usr/local/bin
          cp dist/f1viewer pkg/usr/local/bin/f1viewer

          fpm -s dir -t deb -n f1viewer -v "${VERSION}" -a amd64 -C pkg --prefix=/
          fpm -s dir -t rpm -n f1viewer -v "${VERSION}" -a amd64 -C pkg --prefix=/

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          name: "v${{ env.VERSION }}"
          body_path: RELEASENOTES.md
          files: |
            dist/f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }}
            dist/f1viewer-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.archive_ext }}.sha256
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
